### ISSUE TITLE
What are the allowed request quotas?

### ISSUE THREAD

**Issue by mmisztal1980** [osm-fr/osm-polygons-generation#20]
I'm working on importing geometries for multiple admin subdivisions for a country. When I import the data from your service, I'm getting a HTTP 429 (too many requests). What are the allowed request quotas? The HttpResponse does not contain a `Retry-After` header either

**Comment by jocelynj** [comment]
I don't remember any limitation on the webserver configuration. I need to check logs - do you have a time where you saw this HTTP 429 error?

**Comment by jocelynj** [comment]
We are using the default apache configuration, so I would say that ~100 parallel requests is the maximum. I would recommend to not go higher than 10-20 parallel requests, as the computations can be a bit heavy.
