### ISSUE TITLE
ST_Simplify vs PreserveTopology

### ISSUE THREAD

**Issue by flohoff** [osm-fr/osm-polygons-generation#6]
Hi,
ich see the Documentation in the git repo contains the ST_SimplifyPreserveTopology although the Website says ST_Simplify.

The result i get is a Multipolygon so i guess its not SimplifyPreserveTopology. The original relation does not contain en-/ or exclaves.

http://polygons.openstreetmap.fr/get_geojson.py?id=73347&params=0.020000-0.005000-0.005000

Flo

**Comment by jocelynj** [comment]
I've updated the SQL request to the real request used by the tool:
```
ST_Union(ST_MakeValid(ST_SimplifyPreserveTopology(geom, 0.00001)), ST_Buffer(ST_SimplifyPreserveTopology(ST_SnapToGrid(ST_Buffer(geom, X), Y), Z)))
```
